# Generated by Django 4.0.5 on 2023-02-11 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ss', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='url',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='urls', to=settings.AUTH_USER_MODEL),
        ),
    ]
